### ISSUE TITLE
Пробую слово "товар"

### ISSUE THREAD

**Issue by vruzin** [georgy7/russian_nouns#10]
Получаю:

|      ед   |     множ   |
|-----------|------------|
| ["товар"] | ["товари"] |
| ["товара"] | ["товар"] |
| ["товару"] | ["товарям"] |
| ["товар"] | ["товари"] |
| ["товаром"] | ["товарями"] |
| ["товаре"] | ["товарях"] |
| ["товаре"]| - |

Хочется исправления )))

**Comment by georgy7** [comment]
Добрый день.
По-видимому, вы указываете "общий род".
Товар — слово мужского рода.

Примеры слов общего рода:
"бедняга", "левша", "плакса".

Это слова, с которыми можно строить фразы и мужского, и женского рода. Например, "она такая плакса" и "он такой плакса". Оба варианта верны.

Мы можем сказать "этот товар", но не можем сказать "эта товар", поэтому товар — не общего рода.

При указании мужского рода слово склоняется правильно.

**Comment by vruzin** [comment]
Ясно... Я думал система сама определяет... я просто хотел найти модуль, который просто пишет название во множественном числе. Но не так как в i18n, а именно с точки зрения морфологии правильно... не выбирая ни склонения, ничего... просто чтоб на полном автомате работало

**Comment by georgy7** [comment]
Я делал нечто близкое для демонстрационного андроид-приложения, но там всё равно можно было менять свойства леммы вручную.

Это делается так. Берется частотный словарь русского языка, оттуда, например, первые 1-5 тысяч слов с родом и, желательно, одушевленностью. При нахождении в этом списке, опции берутся оттуда. Если в этом списке слова нет, эвристика вроде "если последняя согласная, значит мужской, о — средний, а — женский" (для существительных).

Проблемы обязательно возникнут, поскольку существуют омонимы, которые иногда склоняются по-разному.
